# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20161116_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='time_scanned',
            field=models.IntegerField(default=0),
        ),
    ]
