# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20161025_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='loc_name',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
