# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20161031_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='person_scanned',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='scan_date_time',
        ),
        migrations.AddField(
            model_name='item',
            name='person_scanned',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='time_scanned',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
