# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_device_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
        migrations.RemoveField(
            model_name='locdev',
            name='dummy_field',
        ),
    ]
