# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20161101_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('model_number', models.CharField(max_length=200)),
                ('admin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LocDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Device')),
            ],
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question_associated_with',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='item',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='loc_ass',
        ),
        migrations.RemoveField(
            model_name='item',
            name='person_scanned',
        ),
        migrations.RemoveField(
            model_name='item',
            name='time_scanned',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user_assigned',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questions_loc',
        ),
        migrations.AddField(
            model_name='choice',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='person_scanned',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='time_scanned',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='admin',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='user_assigned',
            field=models.CharField(default=100, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Device'),
        ),
        migrations.AlterField(
            model_name='question',
            name='item_assoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Device'),
        ),
        migrations.AddField(
            model_name='locdev',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Location'),
        ),
    ]
