# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20161103_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='location_assoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Location'),
        ),
    ]
