# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('scan_date_time', models.DateTimeField(verbose_name='datetime answered')),
                ('person_scanned', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_barcode_num', models.IntegerField(default=0)),
                ('item_type', models.CharField(max_length=200)),
                ('user_assigned', models.CharField(max_length=200)),
                ('admin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_barcode_num', models.IntegerField(default=0)),
                ('loc_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('item_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Item')),
                ('questions_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Location')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='loc_ass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Location'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question_associated_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
