# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='item_assoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Item'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questions_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Location'),
        ),
    ]
